'\" t
.\"     Title: jobrnr
.\"    Author: Rob Donnelly
.\" Generator: Asciidoctor 2.0.15
.\"      Date: 2021-05-26
.\"    Manual: Jobrnr Manual
.\"    Source: Jobrnr v1.1.0
.\"  Language: English
.\"
.TH "JOBRNR" "5" "2021-05-26" "Jobrnr v1.1.0" "Jobrnr Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
jobrnr \- job description file format
.SH "SYNOPSIS"
.sp
The Jobrnr job description file format is an internal \c
.URL "http://martinfowler.com/bliki/DomainSpecificLanguage.html" "DSL" ""
writen in
.URL "https://www.ruby\-lang.org" "Ruby" ""
used to describe a
.URL "https://en.wikipedia.org/wiki/Directed_acyclic_graph" "DAG" ""
of jobs.
.SH "KEYWORDS"
.sp
\fBjob\fP \fIid\fP, [\fIprerequisite(s)\fP], \fI&block\fP
.RS 4
Defines a job.
.sp
\fBexecute\fP \fIString\fP | \fIProc\fP
.RS 4
Defines the command a job will execute.
.sp
The argument can be a String or a Proc that returns a String.
If a String is given, it is evaluated when a job is executed.
This allows command Strings to be interpolated at execution time.
If a Proc is given, it is called when a job instance is executed.
.sp
Seed substitution is then performed on the resulting command String.
The following subsitutions are supported:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
"__SEED%x__" \(em Substituted with a random 32\-bit hexadecimal integer
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
"__SEED%d__" \(em Substituted with a random 32\-bit decimal integer
.RE
.RE
.sp
\fBrepeat\fP \fIInteger\fP
.RS 4
Defines the number of times a job should be repated.
.RE
.RE
.sp
\fBimport\fP \fIprefix\fP, \fIfilename\fP
.RS 4
Imports jobs from another job description (*.jr) file.
.RE
.SH "OBJECTS"
.sp
\fBjobrnr_options\fP
.RS 4
.sp
\fBoutput_directory=\fP
.RS 4
Path to output directory.
Relative paths are relative to \fBPWD\fP.
Environment variables are expanded.
This value will override any \fB\-\-output\-directory\fP option \fIbefore\fP the job description file on the command\-line.
This value can be overriden by any \fB\-\-output\-directory\fP option \fIafter\fP the job description file on the command\-line.
.RE
.RE
.SH "EXAMPLES"
.SS "A simple job"
.sp
.if n .RS 4
.nf
.fam C
job :simple do
  execute "sleep 1"
end
.fam
.fi
.if n .RE
.SS "A repeating job"
.sp
.if n .RS 4
.nf
.fam C
job :repeat do
  execute "sleep 1"
  repeat 5
end
.fam
.fi
.if n .RE
.SS "A proc command"
.sp
The examples prior to this passed a command string to \fBexecute\fP.
This example passes a proc.
The proc returns a command string.
.sp
The proc is evaluated at job execution time instead of at job definition time.
This allows dynamic control of the command string.
.sp
In this example, each repitition will execute a different command.
.sp
.if n .RS 4
.nf
.fam C
job :block do
  execute { "sleep " + rand(10) }
  repeat 5
end
.fam
.fi
.if n .RE
.SS "An immediate interpolation command"
.sp
The command string interpolated at job definition time so all 5 repititions will execute the same command.
.sp
.if n .RS 4
.nf
.fam C
job :immediate_evaluation do
  execute "sleep #{rand(10)}"
  repeat 5
end
.fam
.fi
.if n .RE
.SS "A delayed interpolation command"
.sp
The command string is interpolated at job execution time so each repitition will execute a different command.
.sp
.if n .RS 4
.nf
.fam C
job :delayed_evaluation do
  execute \(aqsleep #{rand(10)}\(aq
  repeat 5
end
.fam
.fi
.if n .RE
.SS "Seed substitution"
.sp
The command string is substituted at job execution time with a random seed.
Each repitition will be substituted with a different seed.
.sp
.if n .RS 4
.nf
.fam C
job :seed_substitution do
  execute "echo 0x__SEED%x__"
  repeat 5
end
.fam
.fi
.if n .RE
.SS "Prerequisites"
.sp
The compile job is a prerequisite of the run job.
.sp
.if n .RS 4
.nf
.fam C
job :compile do
  execute \(aqmake compile\(aq
end

job :run, :compile do
  execute \(aqmake run\(aq
end
.fam
.fi
.if n .RE
.SS "Import"
.sp
Import jobs from \(aqb.jr\(aq with prefix \(aqa\(aq.  If \(aqb.jr\(aq has job \(aqc\(aq, it will be imported as \(aqa_c\(aq.
.sp
.if n .RS 4
.nf
.fam C
import \(aqa\(aq, \(aqb.jr\(aq
.fam
.fi
.if n .RE
.SS "Imported Jobs"
.sp
Imported jobs can be referenced in the form of <import\-prefix>_<job\-id>.
.sp
This example assumes \(aqimports.jr\(aq contains a \(aqcompile\(aq job.
.sp
.if n .RS 4
.nf
.fam C
import \(aqimport\(aq, \(aqimports.jr\(aq

job :run, :import_compile do
  execute \(aqmake run\(aq
end
.fam
.fi
.if n .RE
.SS "Output Directory"
.sp
Place output logs in the $RESULTS/jobs directory.
.sp
.if n .RS 4
.nf
.fam C
job :example do
  execute \(aqsleep 10\(aq
end

jobrnr_options.output_directory = "$RESULTS/jobs"
.fam
.fi
.if n .RE
.SH "SEE ALSO"
.sp
\fBjobrnr\fP(1)
.SH "AUTHOR"
.sp
Rob Donnelly