= jobrnr(1)
Rob Donnelly
:version: v2.0.0-beta.2
:doctype: manpage
:manmanual: Jobrnr Manual
:mansource: Jobrnr {version}
:copyright: 2021

== Name

jobrnr - runs jobs

== Synopsis

**jobrnr** [_OPTION_]... _FILE_

== Description

Jobrnr runs jobs.

* A job can have prerequisite jobs.
* A job can be repeated many times.
* A job can be passed a random seed.
* Jobs are run simultaneously where possible.
* Additional functionality can be added via plug-ins.

== Files

The input file should be a valid *jobrnr*(5) source file.
Source files are typically named <name>.jr (e.g. example.jr).

== Options

=== General options

*-d, --output-directory*=_directory_::
The directory where results will be placed.
Will be created if it does not already exist.
Overrides the *JOBRNR_OUTPUT_DIRECTORY* environment variable.
Default: *$PWD*.

*-f, --max-failures*=_failures_::
The number of failures to allow before disabling execution of new jobs.
All running jobs will be allowed to finish before terminating.
Value of `0` effectively disables this setting.
Overrides the *JOBRNR_MAX_FAILURES* environment variable.
Default: 0 (disabled)

*-j, --max-jobs*=_jobs_::
The number of jobs to run simultaneously.
Overrides the *JOBRNR_MAX_JOBS* environment variable.
Default: 8

*--no-recycle*::
Prevents recycling of job slots.
By default, slots for passing jobs are recycled for future jobs while slots for failing jobs are not recycled.
The *--no-recycle* option changes the default to prevent recycling of job slots for passing jobs as well as failing jobs.

=== Debug options

:dot: http://www.graphviz.org/content/dot-language

*--dot*::
Display the job graph to `STDOUT` in Graphviz {dot}[DOT] format and exit.

*--dry-run*::
Don't execute any jobs.
Only print what would be executed.
Set *--max-jobs* to a larger value to make this faster.

*-v, --verbose*::
Enable debug output.

=== Help options

*-h*::
Display short help and exit.

*--help*::
Display long help and exit.

*--help-format*::
Display job description file format help and exit.

*--help-plugin*::
Display plugin API help and exit.

== Environment

*JOBRNR_PLUGIN_PATH*::
A semicolon separated list of absolute path(s) to Jobrnr plug-ins.

*JOBRNR_OUTPUT_DIRECTORY*::
The directory where results will be placed.
Will be created if it does not exist.
The *-d* option takes precendence over this value.
Default: *$PWD*

*JOBRNR_MAX_FAILURES*::
The number of failures to allow before terminating.
The *-f* option takes precendence over this value.
Default: 0 (disabled)

*JOBRNR_MAX_JOBS*::
The number of jobs to run simultaneously.
The *-j* option takes precendence over this value.
Default: 8

== Copyright

Jobrnr is Copyright (C) {copyright} Rob Donnelly

== See Also

*jobrnr*(5)
