= jobrnr(5)
Rob Donnelly
:version: v2.0.0-beta
:doctype: manpage
:manmanual: Jobrnr Manual
:mansource: Jobrnr {version}

:du: __

== Name

jobrnr - job description file format

== Synopsis

:dsl: http://martinfowler.com/bliki/DomainSpecificLanguage.html
:ruby: https://www.ruby-lang.org
:dag: https://en.wikipedia.org/wiki/Directed_acyclic_graph

The Jobrnr job description file format is an internal {dsl}[DSL] writen in {ruby}[Ruby] used to describe a {dag}[DAG] of jobs.

== Keywords

*job* _id_, [_prerequisite(s)_], _&block_::
Defines a job.

*execute* _String_ | _Proc_::::
Defines the command a job will execute.
+
The argument can be a String or a Proc that returns a String.
If a String is given, it is evaluated when a job is executed.
This allows command Strings to be interpolated at execution time.
If a Proc is given, it is called when a job instance is executed.
+
Seed substitution is then performed on the resulting command String.
The following subsitutions are supported:
+
* "{du}SEED%x{du}" -- Substituted with a random 32-bit hexadecimal integer
* "{du}SEED%d{du}" -- Substituted with a random 32-bit decimal integer

*repeat* _Integer_::::
Defines the number of times a job should be repated.

*import* _prefix_, _filename_::
Imports jobs from another job description (*.jr) file.

== Objects

*jobrnr_options*::

*output_directory=*::::
Path to output directory.
Relative paths are relative to *PWD*.
Environment variables are expanded.
This value will override any *--output-directory* option _before_ the job description file on the command-line.
This value will be overriden by any *--output-directory* option _after_ the job description file on the command-line.

== Examples

=== A simple job

[source,ruby]
----
job :simple do
  execute "sleep 1"
end
----

=== A repeating job

[source,ruby]
----
job :repeat do
  execute "sleep 1"
  repeat 5
end
----

=== A proc command

The examples prior to this passed a command string to *execute*.
This example passes a proc.
The proc returns a command string.

The proc is evaluated at job execution time instead of at job definition time.
This allows dynamic control of the command string.

In this example, each repitition will execute a different command.

[source,ruby]
----
job :block do
  execute { "sleep " + rand(10) }
  repeat 5
end
----

=== An immediate interpolation command

The command string interpolated at job definition time so all 5 repititions will execute the same command.

[source,ruby]
----
job :immediate_evaluation do
  execute "sleep #{rand(10)}"
  repeat 5
end
----

=== A delayed interpolation command

The command string is interpolated at job execution time so each repitition will execute a different command.

[source,ruby]
----
job :delayed_evaluation do
  execute 'sleep #{rand(10)}'
  repeat 5
end
----

=== Seed substitution

The command string is substituted at job execution time with a random seed.
Each repitition will be substituted with a different seed.

[source,ruby]
----
job :seed_substitution do
  execute "echo 0x__SEED%x__"
  repeat 5
end
----

=== Prerequisites

The compile job is a prerequisite of the run job.

[source,ruby]
----
job :compile do
  execute 'make compile'
end

job :run, :compile do
  execute 'make run'
end
----

=== Import

Import jobs from 'b.jr' with prefix 'a'.  If 'b.jr' has job 'c', it will be imported as 'a_c'.

[source,ruby]
----
import 'a', 'b.jr'
----

=== Imported Jobs

Imported jobs can be referenced in the form of <import-prefix>_<job-id>.

This example assumes 'imports.jr' contains a 'compile' job.

[source,ruby]
----
import 'import', 'imports.jr'

job :run, :import_compile do
  execute 'make run'
end
----

=== Output Directory

Place output logs in the $RESULTS/jobs directory.

[source,ruby]
----
job :example do
  execute 'sleep 10'
end

jobrnr_options.output_directory = "$RESULTS/jobs"
----

== See Also

*jobrnr*(1)
