AllCops:
  TargetRubyVersion: 2.7
  DisplayCopNames: true
  NewCops: enable

Layout/LineLength:
  Max: 120

Style/CommandLiteral:
  EnforcedStyle: percent_x
Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArrayLiteral:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false
Style/TrailingCommaInArguments:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false
