AllCops:
  TargetRubyVersion: 2.7
  DisplayCopNames: true
  NewCops: enable

Metrics/LineLength:
  Max: 120

Style/TrailingCommaInArrayLiteral:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false
